### ISSUE TITLE
Youtube player timeline doesnt follow up properly when using Ruffle emulator

### ISSUE THREAD

**Issue by ArielChandia2** [IdioticSniper/externaltube#2]
https://file.garden/YbJeMftBp0P7hfIi/ruffleerror

The timeline doesnt show up properly with using current browsers with ruffle support, the timeline doesnt show up the current second you are in and it doesnt show up the loaded parts either, it shows up only as a long grey rectangle all the way, Making it hard to know where its the video its currently playing.

For anyone not aware this is how it supposed to look like using a the actual flash player:
https://file.garden/YbJeMftBp0P7hfIi/flashplayercorect

**Comment by IdioticSniper** [comment]
Ruffle issue - nothing to do with the website's code or video player
